# Generated by Django 5.2 on 2026-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_prdoucer",
            new_name="is_producer",
        ),
        migrations.RemoveField(
            model_name="producer",
            name="genres",
        ),
        migrations.AddField(
            model_name="producer",
            name="category",
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
