# Generated by Django 5.2 on 2026-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_is_prdoucer_user_is_producer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
    ]
