# Generated by Django 5.2 on 2026-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="rating",
            field=models.FloatField(),
        ),
    ]
