# Generated by Django 5.2 on 2026-03-30 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_producer_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="played_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="producer",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
