# Generated by Django 5.2 on 2026-03-31 10:30

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_producer_played_time_alter_producer_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="location",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
