# Generated by Django 5.2 on 2026-04-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_producer_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="producer",
                to="users.producer",
            ),
        ),
    ]
