# Generated by Django 5.2 on 2026-04-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_music_published_date_music_is_published"),
        ("users", "0008_alter_producer_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="producer",
                to="app.category",
            ),
        ),
    ]
