# Generated by Django 5.2 on 2026-04-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
