# Generated by Django 5.2 on 2026-04-16 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
