# Generated by Django 5.2 on 2026-04-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_music_album_alter_music_artist_and_more"),
        ("users", "0014_alter_producer_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="producer",
                to="app.category",
            ),
        ),
    ]
