# Generated by Django 5.2 on 2026-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_music_producer_alter_music_artist_and_more"),
        ("users", "0015_alter_producer_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Producer",
            new_name="Artist",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_producer",
            new_name="is_artist",
        ),
    ]
