# Generated by Django 5.2 on 2026-04-25 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_music_auto_fill_producer"),
        ("users", "0016_rename_producer_artist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to="app.category",
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
