# Generated by Django 5.2 on 2026-05-05 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 099 and contain 11 digits.",
                        regex="^099\\d{8}$",
                    )
                ],
            ),
        ),
    ]
