services:
  backend:
    build: .
    container_name: django
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5001:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
  postgres_db:
    image: postgres:16
    container_name: soundora_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: alidb
      POSTGRES_PASSWORD: ali72387238
      POSTGRES_DB: soundora
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresqldata
  pgadmin_gui:
    image: dpage/pgadmin4
    container_name: local_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      - postgres_db

volumes:
  pg_data:
  smtp4dev-data: