# Generated by Django 5.2 on 2026-03-29 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="users.producer",
            ),
        ),
    ]
