# Generated by Django 5.2 on 2026-03-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="app.category",
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="cover_image",
            field=models.ImageField(upload_to="cover-images/"),
        ),
        migrations.AlterField(
            model_name="music",
            name="lyrics",
            field=models.TextField(blank=True, null=True),
        ),
    ]
