# Generated by Django 5.2 on 2026-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_music_category_alter_music_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="published_date",
        ),
        migrations.AddField(
            model_name="music",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
