# Generated by Django 5.2 on 2026-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_music_published_date_music_is_published"),
        ("users", "0009_alter_producer_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="music",
            old_name="created_date",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="music",
            name="name",
        ),
        migrations.AddField(
            model_name="music",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="music",
            name="producer",
        ),
        migrations.AddField(
            model_name="music",
            name="producer",
            field=models.ManyToManyField(related_name="musics", to="users.producer"),
        ),
    ]
