# Generated by Django 5.2 on 2026-04-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_created_date_music_uploaded_at_and_more"),
        ("users", "0009_alter_producer_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProducerMusicList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "music",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.music"
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.producer"
                    ),
                ),
            ],
        ),
    ]
