# Generated by Django 5.2 on 2026-04-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_producermusiclist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProducerMusicList",
        ),
    ]
