# Generated by Django 5.2 on 2026-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_delete_producermusiclist"),
        ("users", "0009_alter_producer_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="music",
            name="artist",
            field=models.ManyToManyField(
                related_name="artistmusic", to="users.producer"
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="producer",
            field=models.ManyToManyField(
                related_name="producermusic", to="users.producer"
            ),
        ),
    ]
