# Generated by Django 5.2 on 2026-04-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_album_music_artist_alter_music_producer"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="app.album",
            ),
            preserve_default=False,
        ),
    ]
