# Generated by Django 5.2 on 2026-04-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_music_album"),
        ("users", "0010_user_full_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="app.album",
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.ManyToManyField(
                blank=True, related_name="artistmusic", to="users.producer"
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="app.category",
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="cover-images/"),
        ),
        migrations.AlterField(
            model_name="music",
            name="producer",
            field=models.ManyToManyField(
                blank=True, related_name="producermusic", to="users.producer"
            ),
        ),
    ]
