# Generated by Django 5.2 on 2026-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_music_album_alter_music_artist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="auto_fill_album",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="music",
            name="auto_fill_artist",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="music",
            name="auto_fill_coverimage",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="music",
            name="auto_fill_producer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="music",
            name="auto_fill_title",
            field=models.BooleanField(default=True),
        ),
    ]
