# Generated by Django 5.2 on 2026-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_music_auto_fill_album_music_auto_fill_artist_and_more"),
        ("users", "0015_alter_producer_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="producer",
        ),
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.ManyToManyField(
                blank=True, related_name="artist", to="users.producer"
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="auto_fill_album",
            field=models.BooleanField(default=True, verbose_name="Album Auto-Fill"),
        ),
        migrations.AlterField(
            model_name="music",
            name="auto_fill_artist",
            field=models.BooleanField(default=True, verbose_name="Artist Auto-Fill"),
        ),
        migrations.AlterField(
            model_name="music",
            name="auto_fill_coverimage",
            field=models.BooleanField(
                default=True, verbose_name="CoverImage Auto-Fill"
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="auto_fill_producer",
            field=models.BooleanField(default=True, verbose_name="Producer Auto-Fill"),
        ),
        migrations.AlterField(
            model_name="music",
            name="auto_fill_title",
            field=models.BooleanField(default=True, verbose_name="Title Auto-Fill"),
        ),
    ]
