# Generated by Django 5.2 on 2026-04-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_music_producer_alter_music_artist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="auto_fill_producer",
        ),
    ]
