# Generated by Django 5.2 on 2026-05-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_music_auto_fill_producer"),
        ("users", "0020_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ManyToManyField(related_name="album", to="users.artist"),
        ),
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.ManyToManyField(
                blank=True, related_name="musics", to="users.artist"
            ),
        ),
        migrations.RemoveField(
            model_name="music",
            name="category",
        ),
        migrations.AddField(
            model_name="music",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="musics", to="app.category"
            ),
        ),
    ]
