# Generated by Django 5.2 on 2026-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_playlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("windows", models.IntegerField()),
                ("mac", models.IntegerField()),
                ("iphone", models.IntegerField()),
                ("android", models.IntegerField()),
                ("other", models.IntegerField()),
            ],
        ),
    ]
