# Generated by Django 5.2 on 2026-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stats",
            name="windows",
        ),
        migrations.AddField(
            model_name="stats",
            name="win",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stats",
            name="android",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stats",
            name="iphone",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stats",
            name="mac",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stats",
            name="other",
            field=models.IntegerField(default=0),
        ),
    ]
