# Generated by Django 5.2 on 2026-05-11 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_remove_stats_windows_stats_win_alter_stats_android_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_music",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Likes",
            ),
        ),
    ]
