# Generated by Django 5.2 on 2026-05-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_remove_music_likes_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="musics", to="app.category"
            ),
        ),
    ]
