# Generated by Django 5.2 on 2026-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_music_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="musics", to="app.category"
            ),
        ),
    ]
